### ISSUE TITLE
[Feature] Model Distortion for Software Emulation

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/quakespasm#19]
I'm forever greatful that you're adding software rendering emulation to your fork of Quakespasm. It's something I've been wanting for a long time.

Something that is missing though is that distinct model distortion, particularly noticeable on weapons (and probably on other models as well).

Here's the shotgun for example.

What it looks like in Ironwail:
![image](https://user-images.githubusercontent.com/29780788/149831987-99ae1e41-977f-46a6-a726-5382be0133e1.png)

What it looks like in the original renderer (1024x768):
![image](https://user-images.githubusercontent.com/29780788/149832117-00b995b1-f9a5-4af0-b4c6-9201afe63f21.png)

**Comment by andrei-drexler** [comment]
I actually had this in my initial implementation, but I ended up removing it to avoid overcomplicating the shaders for a minor detail that (I thought) nobody would notice. I guess I was wrong :) Fixed in https://github.com/andrei-drexler/quakespasm/commit/1976510adf6bf296b450bae6b88977d527a4626d & https://github.com/andrei-drexler/quakespasm/commit/7fd68e72c58b2a659e4fff4b06ad0e256314dbfa:

| IW 0.3.0 | https://github.com/andrei-drexler/quakespasm/commit/7fd68e72c58b2a659e4fff4b06ad0e256314dbfa | Quake 1.06 |
|---|---|---|
| <img src="https://user-images.githubusercontent.com/5121829/150699659-6127f68d-e149-4f24-a8b1-c375ab2b5a30.png"/> | <img src="https://user-images.githubusercontent.com/5121829/150700471-d0fb1eea-228b-4588-85ba-e29a9a703925.png"/> | <img src="https://user-images.githubusercontent.com/5121829/150699677-b761478e-d934-4e1d-b9ac-e13259fad641.png"/> |

**Comment by OpenRift412** [comment]
> I actually had this in my initial implementation, but I ended up removing it to avoid overcomplicating the shaders for a minor detail that (I thought) nobody would notice. I guess I was wrong :) Fixed in [1976510](https://github.com/andrei-drexler/quakespasm/commit/1976510adf6bf296b450bae6b88977d527a4626d) & [7fd68e7](https://github.com/andrei-drexler/quakespasm/commit/7fd68e72c58b2a659e4fff4b06ad0e256314dbfa):
> 
> IW 0.3.0	[7fd68e7](https://github.com/andrei-drexler/quakespasm/commit/7fd68e72c58b2a659e4fff4b06ad0e256314dbfa)	Quake 1.06
> ![](https://user-images.githubusercontent.com/5121829/150699659-6127f68d-e149-4f24-a8b1-c375ab2b5a30.png)	![](https://user-images.githubusercontent.com/5121829/150700471-d0fb1eea-228b-4588-85ba-e29a9a703925.png)	![](https://user-images.githubusercontent.com/5121829/150699677-b761478e-d934-4e1d-b9ac-e13259fad641.png)

If you're gonna include an old-school option for the purists, you know they'll notice the inconsistencies. ;)
Anyway, thanks for the update!
