### ISSUE TITLE
1.06-style browned menu background palette on "raw" 8-bit setting

### ISSUE THREAD

**Issue by OpenRift412** [andrei-drexler/quakespasm#20]
I think a good quality of life feature to add to this new software emulation would be to have the "raw" option use the old 1.06 browned background fade. Also not having the fade apply on the console background would be nice as well.

**Comment by andrei-drexler** [comment]
When the menu fade is applied the colors aren't yet palettized, so the effect has to be approximated through more conventional means. It should be much closer to the 1.06 look after commit https://github.com/andrei-drexler/quakespasm/commit/7efd6a48443e299c930ce38155edcb797a834ab1, though:

| IW 0.3.0 | https://github.com/andrei-drexler/quakespasm/commit/7efd6a48443e299c930ce38155edcb797a834ab1 | Quake 1.06 |
|---|---|---|
|<img src="https://user-images.githubusercontent.com/5121829/150647988-8361daed-3dcb-4bee-97dd-bf3d426e6df6.png"/>|<img src="https://user-images.githubusercontent.com/5121829/150648033-fe46c006-41f4-454e-8eed-80ecd7abed0a.png"/>|<img src="https://user-images.githubusercontent.com/5121829/150648075-547c9e0d-bdf4-4cba-9b52-ece05bbb3573.png"/>|

PS in my initial implementation the fade wasn't applied on top the console, just like in 1.06, but the menu text was a bit harder to read, which is why the behavior is slightly different now.
